# -*- coding: utf-8 -*-
"""Spam detecter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqq3WxubqTiQwF-BA1CpQuuSrA4l_DlI
"""

# load, Explore and Plot the Data
import numpy as np
import pandas as pd
import re
import string
import seaborn as sns
import matplotlib.pyplot as plt

# suppress display of warnings
import warnings
warnings.filterwarnings("ignore")

## Reading the given dataset
data = pd.read_excel("/content/spam_ham_dataset.csv.xlsx", names=["label", "message"])

data.head()

data.shape

# Checking for null values
data.isnull().sum()

# Checking for duplicate values
data.duplicated().sum()

"""*178 duplicate rows found in the dataset and need to remove them.*"""

# Drop duplicates
data = data.drop_duplicates()

data.duplicated().sum()

"""# **Now, Data Analysis**"""

data['label'].value_counts()

plt.pie(data['label'].value_counts(), labels = ['ham', 'spam'], colors = ['Red', 'yellow'], autopct='%0.2f')

"""**So, we can observe that dataset has 70.72% ham messages whereas 29.28% messages are spam.**"""

# 1st meassage
data['message'][0]

# total no. of characters
data['num_characters'] = data['message'].apply(len)

data.head()

import nltk # Natural Language Toolkit
nltk.download('punkt_tab')

# words tokenization
data['message'].apply(lambda x: nltk.word_tokenize(x))

# total no. of words
data['num_words'] = data['message'].apply(lambda x:len(nltk.word_tokenize(x)))
data.head()

# Number of sentences
data['num_sentences']=data['message'].apply(lambda x: len(nltk.sent_tokenize(x)))

data.head()

# Ham messages
data[data['label'] == 'ham'][['num_characters','num_words','num_sentences']].describe()

# Spam messages
data[data['label']=='spam'][['num_characters','num_words','num_sentences']].describe()

"""We can clearly see that spam messages have more characters and words comapare to ham messages."""

plt.figure()
sns.histplot(data[data['label'] == 'ham']['num_characters'],color ='green')
sns.histplot(data[data['label'] == 'spam']['num_characters'],color = 'red')

# for words
plt.figure()
sns.histplot(data[data['label'] == 'ham']['num_words'],color = 'green')
sns.histplot(data[data['label'] == 'spam']['num_words'],color = 'red')

"""# **Word Cloud**"""

!pip install wordcloud

from wordcloud import WordCloud

ham_msg_text = data[data.label == 'ham'].message
spam_msg_text = data[data.label == 'spam'].message

## Word Cloud for Ham messages

plt.figure()

wc = WordCloud().generate(" ".join(ham_msg_text))
plt.imshow(wc)

## Word Cloud for Spam MSGs

plt.figure()

wc = WordCloud(width = 1500, height = 900, max_words = 2500).generate(" ".join(spam_msg_text))
plt.imshow(wc, interpolation='bilinear')

"""# **Data Pre-Processing**"""

data['message'][5]

"""1. Remove Punctuation"""

def remove_punc(text):
  trans = str.maketrans('', '', string.punctuation)
  return text.translate(trans)

data['message'] = data['message'].apply(remove_punc)

data['message'][5]

"""2. Remove Special Characters"""

def remove_noise(text):
  t = re.sub('[^a-zA-Z]', ' ', text)
  return t

data['message'] = data['message'].apply(remove_noise)

data['message'][5]

"""3. Remove Stopwords"""

nltk.download('stopwords')

from nltk.corpus import stopwords
sw = stopwords.words('english')

sw

def remove_sws(text):
  s = [word.lower() for word in text.split() if word.lower() not in sw]
  return " ".join(s)

data['message'] = data['message'].apply(remove_sws)

data['message'][5]

"""4. Lemmatization"""

nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemma(text):
  l = [lemmatizer.lemmatize(word) for word in text.split()]
  return " ".join(l)

data['message'] = data['message'].apply(lemma)

data['message'][5]

data.head()

"""5. Label Encoder"""

from sklearn.preprocessing import LabelEncoder
encoder =LabelEncoder()

data['label']=encoder.fit_transform(data['label'])

data.head()

# Select only the relevant columns for building model

data = data[['label','message']]

data.head()

"""# **3. Feature Extraction for Converting Word to Vectors**
*Apply TF-IDF Vectorizer to convert word into Vectors.*
"""

from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=3000)

X = tf.fit_transform(data['message']).toarray()
Y = data['label']

X

Y

# Splitting the data into train and test

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 32)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

"""# **4. Model Building & Evaluation**"""

from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create the instance of Naive Bayes
clf = BernoulliNB()

# Fit the data
clf.fit(X_train, Y_train)

# Making prediction
Y_pred = clf.predict(X_test)

# Evaluation
print("Accuracy Score: ", accuracy_score(Y_test, Y_pred))

print(classification_report(Y_test, Y_pred))

# Plot the Confusion Matrix

import seaborn as sn
cm = confusion_matrix(Y_test, Y_pred)

plt.figure(figsize = (12,5))
sn.heatmap(cm, annot=True,linewidth = 0.5 , cmap = 'tab20' , fmt='d')
plt.title('Naive Bayes Model Confusion Matrix', size=15)
plt.xlabel('Predicted')
plt.ylabel('Truth')

"""## **5. Save the Model**"""

import pickle
pickle.dump(tf,open('vectorizer.pkl','wb'))
pickle.dump(clf,open('model.pkl','wb'))

!pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501